### ISSUE TITLE
View archived conversations

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#11]
_Menu>'View archived conversations'_ is currently opening to:
`C:\Users\sparks\AppData\Local\blackmirror`
when the expected behaviour was opening to:
`C:\Users\sparks\conversations`

It's fine after first use though, it remembers that I navigated to _C:\Users\sparks\conversations_ manually.

Minor issue only.

**Comment by sorentycho** [comment]
Electron doesn't give good control over this, sadly.
