### ISSUE TITLE
Additional menu items (discoverability issue)

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#13]
>_You can press Shift-Return to swap the current paragraph between 'voices'_

>_Bold, Italic, and 'OtherVoice' (the HTML mark tag, which I use to denote interjection by a third party) available by pressing ctrl+b, ctrl+i, ctrl+o, respectively. A small indicator by the insertion point shows if one of these styles is active._

Sadly these need menu items because first rule of user testing: only turbonerds read help files! 🚀

**Comment by sorentycho** [comment]
All of these things now have menu or context-menu items!
