### ISSUE TITLE
Attempting to open while already open causes exception

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#2]
Attempting to open while already open causes exception, img attached
![err](https://user-images.githubusercontent.com/32550963/31275461-3516ba22-aa8f-11e7-8f44-ed0025ad6a09.png)
Yeah sensible people shouldn't do that, but some monkey tester will and it looks ugly ;)

**Comment by sorentycho** [comment]
Well, clearly you need to have a `C:\tmp` dir on your system. Doesn't everyone? :)

More seriously, this'll get fixed as soon as I move to a CLI handling library that doesn't require such silliness. Opening while open *should* just raise the specified window or open a new conversation picker.

**Comment by SparksJ2** [comment]
Note: if I _do_ have a `C:\tmp`, it opens a new convo picker just fine.

**Comment by sorentycho** [comment]
Supposedly fixed in the latest `master` commit. Can you try it when you get a chance?

**Comment by SparksJ2** [comment]
Just tried it. Works fine now, I have two windows open.

On the 2nd opening, a window opens and closes quickly for a fraction of a second, before showing the voice picker. Cosmetic only.

(check your email, important note re:ID sent to you)

**Comment by sorentycho** [comment]
Closing, then. I think the fractional window must be something about the Windows runtime, there are no create window calls from the second open.
