### ISSUE TITLE
unicode character '🗃' not supported in electron, windows version

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#20]
'🗃' won't show up on my system.

I do have the code-point, in Symbola, but it's only appearing as a box in electron.

**Comment by sorentycho** [comment]
Suspecting encoding-voodoo, I've replaced it with a character entity reference. Any improvement?

**Comment by SparksJ2** [comment]
No joy. Chrome on windows is erratic with unicode support at best, even if you have the code point available it won't search as many fonts as you'd like to try and find it. You could detect windows and force Symbola font, maybe. 😞

**Comment by SparksJ2** [comment]
Since all the current Unicode works (at least for me), I'm closing this for now. I'll keep an eye on it.
