### ISSUE TITLE
Scroll bar colour tweak

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#22]
I've added, in my current version:
```
::-webkit-scrollbar {     
        background-color: #222;
        width: 1em
}

::-webkit-scrollbar-thumb:window-inactive,
::-webkit-scrollbar-thumb {
        background:  black
}
```

to conversation.css as the light gray default scroll bar is a bit of an eyesore to me.

**Comment by sorentycho** [comment]
I've added some default style to the scrollbars in the default stylesheet. Seems to be the done thing these days.
