### ISSUE TITLE
HTML export error in windows 7.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#23]
![htmlerror](https://user-images.githubusercontent.com/32550963/33783229-ce12e200-dc53-11e7-913c-7efd4e0f1dde.png)

The file mentioned does exist there, but I think it's the extra slash at the start there that's breaking it.

**Comment by sorentycho** [comment]
I *think* this may have been due to my trying to use a much-too-bleeding-edge version of electron. Let me know if it still happens after pulling the last few commits? You should have electron 1.8.1 installed, you may have to `npm install` or so to get there.

**Comment by SparksJ2** [comment]
I have a different but similar error now:
![new-error](https://user-images.githubusercontent.com/32550963/33794352-8a467c5c-dcc2-11e7-8fe6-2f252a2328d2.png)
This file exists... but I'd prefer it used the one in /conversations/... but the doubled c:\c:\ means it fails anyway.

**Comment by SparksJ2** [comment]
what why did it close? Oops.

**Comment by sorentycho** [comment]
One more try now with path.normalize. Give it a try again?

**Comment by SparksJ2** [comment]
Nope, exact same error as last time.

**Comment by sorentycho** [comment]
Fix as of f5ee4b97784863a9a666a768c12d160f4fc80e81.
