### ISSUE TITLE
Uttempting to undo a paste makes a mess.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#29]
![undo-fail](https://user-images.githubusercontent.com/32550963/34529192-1cea2bf0-f0a3-11e7-9f5a-6037ef9edb6e.png)

(I know you said this wasn't your fault, but I figure it deserves an issue as a long term problem to keep an eye on.)

**Comment by sorentycho** [comment]
Seems fixed by not stripping SPAN tags on paste.
