### ISSUE TITLE
Help file images not loading

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#3]
![missingimg](https://user-images.githubusercontent.com/32550963/31275666-1eea0532-aa90-11e7-9f0c-658fbae65719.png)

**Comment by sorentycho** [comment]
Hrm. Can you paste me the file paths it's trying to load from the dev console? And what the `base` tag at the top of the page has for a base path?

**Comment by SparksJ2** [comment]
`file:///C:/Users/sparks/AppData/Local/Programs/blackmirror/resources/app.asar/build/icon.png?raw=true`
and
`file://C:\Users\sparks\AppData\Local\Programs\blackmirror\resources\app.asar/`

note `app.asar` doesn't exist and I can't see any .pngs anywhere in /programs/blackmirror/

**Comment by sorentycho** [comment]
Oh, yeah, need to add those to the deploy fileset...

`app.asar` is an artifact of the magic electron-builder does to distribute on Windows and AFAIK isn't supposed to exist.
