### ISSUE TITLE
browserify, use of > vs. -o

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#31]
in `nw-build.sh`,

`npx browserify -x ./common -x ./platform -x js-yaml -x keymaster -x tumblr.js "$base.js" $igv > ../dist/$base.pack.js`, and so on.

Could you use `-o` for output, instead of `>`, as somehow `>` leaves a spurious extra line at the start of output file causing a crash later? I'm using cygwin64 under windows and have been unable to track the problem down, everything else seems fine. It's really weird, certainly a problem on my end, but it would be helpful if you changed it.

**Comment by sorentycho** [comment]
Done!
