### ISSUE TITLE
(Windows) Shift+Return in conversation wip just adds a new line

### ISSUE THREAD

**Issue by LoverIan** [sorentycho/blackmirror#32]
To start off I am on a Win10 using the latest Black Mirror version as of posting this. 10.0.0 iirc.

> By holding Shift, Control, or Alt as you press Return, you can create a paragraph in another voice to allow your other conversant(s) to speak.

Shift+Enter (the equivalent of return on windows iirc) you get the normal result of shift+enter in a text editor.
Same goes for ctrl+enter. Alt+enter sometimes does nothing.
While I had assumed this was the problem having more than two non-default voices does not change this.

> Press Escape alone or together with a modifier key to switch the current paragraph to that voice without creating a new paragraph.

This is additionally an issue.

> Runs in "distraction free" mode by default, which means hidden menu bars on Linux and Windows. Press alt to show the menu bar. It doesn't have to be visible for shortcuts to work. Be sure to explore the menus for useful and hopefully self-explanatory functions!

For whatever reason this does not work on windows. I have both held and pressed both alt keys I have.
I can manually change voices by the right click function though. This prevents me from opening any of the menus outside of what is available through Ctrl+; and right clicks. The full functionality of Conversations and Divinations is not accessible through this however.
![image](https://user-images.githubusercontent.com/40021571/42761315-017ce40e-88c2-11e8-85ea-657dea2ac42c.png)
Is an example of what I can access through this. It is scrollable, but is limited. This does vary slightly when in the Journals area, but doesn't explicitly vary in a WIP Convo.

Let me know if there are any issues from the way I installed (I just extracted the zip and opened the app). Not sure if this is a Win10 issue, or me just being an idiot.

**Comment by LoverIan** [comment]
I have no issue with doing that for you.
I meant to put it somewhere but thank you for making this, it feels like a lovely tool (and the CSS/HTML gives lovely amounts of customization), and it makes me curious if it could be slotted into Twinery like a plugin of sorts.

```
Trying loadFile: C:\Users\Ian\conversations\waeae\_journal.yml
common.pack.js:73   got: Array(0)
common.pack.js:73   got: Array(0)
common.pack.js:71 Globbing: C:\Users\Ian\conversations/resources/**/*.css
common.pack.js:435 C:\Users\Ian\conversations\waeae C:\Users\Ian\conversations
common.pack.js:71 Globbing: C:\Users\Ian\conversations/voices/**.yml
common.pack.js:73   got: Array(1)
common.pack.js:571 <link href="file://C:/Users/Ian/conversations/resources/fonts/fonts.css" type="text/css" rel="stylesheet" media="screen,print">
common.pack.js:73   got: Array(2)
common.pack.js:353 Array(2)0: {styles: {…}, css: "", notes: "uhhhh we want to work on a revic voice", name: "Testing-1-2-3"}1: {styles: {…}, css: "", notes: "", name: "the-me"}length: 2__proto__: Array(0)
common.pack.js:197 sending Window windowIdChange archivelist:C:\Users\Ian\conversations\waeae <<<
common.pack.js:71 Globbing: C:\Users\Ian\conversations\waeae/**/*.convo
common.pack.js:183 got ipc: MessageEventbubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}data: {type: "windowListChange", data: Array(1)}defaultPrevented: falseeventPhase: 0isTrusted: truelastEventId: ""origin: "chrome-extension://ighbdjibadbbimfbckmgobnpdjdokihk"path: [Window]ports: []returnValue: truesource: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}srcElement: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}target: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}timeStamp: 195.00000000698492type: "message"__proto__: MessageEvent
common.pack.js:73   got: Array(0)length: 0__proto__: Array(0)
```

**Comment by sorentycho** [comment]
You're welcome! I hope it'll be useful to you.
Is that all of the text output you get in the console when loading a conversation? There should be a lot more and it should start with something like `Loaded common: Instance_...`.

**Comment by sorentycho** [comment]
If I'm right about what the problem was for you, this issue should be fixed in the latest release.
