### ISSUE TITLE
Hidden menu

### ISSUE THREAD

**Issue by Elias-2** [sorentycho/blackmirror#33]
Hi ! I feel a bit dumb asking this, but I can't make the menu appear ? I can make a journal, but I can't set up the voices. I tried hitting the 'ctrl' and the '+' keys together, I tried 'ctrl' '+' and ';' or any combination of these and it doesn't work. I'm using the windows version on an azerty keyboard. I guess I'm not using the correct keys but I can't find what to press !

**Comment by sorentycho** [comment]
The key combo to show the menu is to hold control and press `;`. Is that not working?

If you're on a Mac, it might be hold Command and press `;`. I don't have a Mac myself, so I can't test that.

**Comment by JanLueppens** [comment]
The key combo maps to a Position on the Keyboard, not a specific Symbol. So for AZERTY the combo is `ctrl + [` and for QWERTZ is `ctrl + ü`.
Hope this helps.

**Comment by SparksJ2** [comment]
This got a clickything on the side of the screen, so you can open the menu with the mouse now. :100:

**Comment by sorentycho** [comment]
The key binding should now be correct even on non-us keyboards, as well.
