### ISSUE TITLE
Slow loading / loading indicators.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#34]
When system load is high, or blackmirror is being opened for the first time after a reboot, it can take 5+ seconds for a windows to load. Journals says “no journals found” during this time which would be a bit disconcerting esp for new users. I think BM could use some sort of “page still loading” indicator.

**Comment by sorentycho** [comment]
Can you try building the installer, and running from that, and tell me how it performs? I *think* this issue is cause by Windows' slow FS performance, which should be fixed by running the app out of a zip archive like the installer does.

**Comment by sorentycho** [comment]
I added a loading spinner, so I'm closing this, but I'm still interested in the performance difference between running from the installed version and running in from source.
