### ISSUE TITLE
Could use some better default voices.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#35]
``other.yml`` is okay, if a bit bare.
``me.yml`` is blank!

Also a demo of some custom css to show what's possible would be nice.

**Comment by SparksJ2** [comment]
https://github.com/sorentycho/blackmirror/blob/master/resources/convoDirSkel/voices/me.yml

``0 lines (0 sloc)  0 Bytes``

Not tried setting up from scratch recently. It's on my list of stuff to try.

**Comment by sorentycho** [comment]
Oh! I'd forgotten that existed! Removed now. If you launch BlackMirror without an existing conversations directory, it creates a `Me.yml` that's filled out with default settings.
