### ISSUE TITLE
Can't create new Journals - already exists even if it doesn't

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#38]
Whatever I enter as a new journal name, BM claims it already exists. I think we had this before, some sort of filename issue regarding Windows conventions?

**Comment by sorentycho** [comment]
Definitely path unpleasantness. Can you paste me the console output that results after trying to create a new journal?

**Comment by SparksJ2** [comment]
```C:\users\sparks\projects\blackmirror\lib\platform.js:42 Trying loadFile: C:\Users\sparks\conversations\we-took-both-pills\_journal.yml
C:\users\sparks\projects\blackmirror\lib\common.js:206 C:\Users\sparks\conversations\we-took-both-pills C:/Users/sparks/conversations
C:\users\sparks\projects\blackmirror\lib\platform.js:42 Trying loadFile: C:\Users\sparks\conversations\_journal.yml
C:\users\sparks\projects\blackmirror\lib\common.js:206 C:\Users\sparks\conversations C:/Users/sparks/conversations
C:\users\sparks\projects\blackmirror\lib\common.js:442 Toast: Journal &ldquo;we-took-both-pills&rdquo; already exists! Refusing to overwrite it. undefined
C:\users\sparks\projects\blackmirror\lib\common.js:422 hiding toast

**Comment by SparksJ2** [comment]
Getting this one again:
``C:\users\sparks\projects\blackmirror\lib\convoPick.js:191 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLBodyElement.document.body.addEventListener (C:\users\sparks\projects\blackmirror\lib\convoPick.js:191)
document.body.addEventListener @ C:\users\sparks\projects\blackmirror\lib\convoPick.js:191
C:\users\sparks\projects\blackmirror\lib\convoPick.js:172 New journal path: C:\Users\sparks\conversations\kvmokgnsb\_journal.yml
C:\users\sparks\projects\blackmirror\lib\common.js:252 loadJournal C:\Users\sparks\conversations\kvmokgnsb\_journal.yml
loadJournal @ C:\users\sparks\projects\blackmirror\lib\common.js:252
document.getElementById.addEventListener @ C:\users\sparks\projects\blackmirror\lib\convoPick.js:173
async function (async)
document.getElementById.addEventListener @ C:\users\sparks\projects\blackmirror\lib\convoPick.js:163
C:\users\sparks\projects\blackmirror\lib\convoPick.js:191 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at HTMLBodyElement.document.body.addEventListener (C:\users\sparks\projects\blackmirror\lib\convoPick.js:191)
document.body.addEventListener @ C:\users\sparks\projects\blackmirror\lib\convoPick.js:191
C:\users\sparks\projects\blackmirror\lib\storage\fs.js:40 Trying loadFile: C:\Users\sparks\conversations\_journal.yml
C:\users\sparks\projects\blackmirror\lib\common.js:508 Toast: Journal &ldquo;kvmokgnsb&rdquo; already exists! Refusing to overwrite it. undefined timeout= undefined undefined undefined
C:\users\sparks\projects\blackmirror\lib\common.js:511 toast timeout was undefined``
