### ISSUE TITLE
Closing vs quitting?

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#4]
_"If you quit BlackMirror via the Quit menu command instead of closing all open windows, it will remember what conversation windows you had open, and restore them next time you run it."_ 

While it IS opening the last convo, it's also opening the voice picker precisely on top of it, which means you won't see it unless you're paying proper attention.

As a secondary issue, having window>close and menu>quit have different behaviours isn't very intuitive.

**Comment by sorentycho** [comment]
Calling this a consequence of #2  for the moment.

**Comment by sorentycho** [comment]
Update: opening the voice picker on execution-with-no-arguments is actually desirable behavior, but needs to not hide the rest of the session.
