### ISSUE TITLE
Vertical line spacing when printing.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#41]
It's minor / low priority, but printing to pdf crushes vertical line spacing rather. The editor shows about 2 line-heights between paragraphs, but the pdf only has one. It's a bit cramped.

**Comment by sorentycho** [comment]
I can't reproduce this. Are you sure you don't have any extra css hanging around your conversations directory?

**Comment by SparksJ2** [comment]
Found it, but it's not my .css!
In the default ``style.css``:
```
* On startup, BlackMirror will scan this directory for .css files, load them,

{blah blah blah}

@media print {
  .conversation p {
    padding: 0 !important;
    background: white !important;
    color: black !important;
  }
}

{more blah}
```

that's where the padding went!

**Comment by SparksJ2** [comment]
note this might also break the menu options to print with dark text / white background, not sure.

**Comment by sorentycho** [comment]
Oh, that's a leftover from the old create-a-skeleton-convo-dir thing. You can safely delete it, unless you've edited it or want there to be no spacing :stuck_out_tongue:
