### ISSUE TITLE
Right click menu on text to 'Edit voice whatevername' only works when done twice.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#43]
Right click menu on text to 'Edit voice whatevername', first attempt always fails, second attempt always works.

If I close the voice editor, and keep trying, same behaviour again, first attempt always fails, second attempt always works.

No obvious console errors, can you reproduce?

**Comment by sorentycho** [comment]
Hmmm...working for me. What happens on failure (if anything at all)?

**Comment by SparksJ2** [comment]
Unable to reproduce this anymore in the latest version. Seems ok now.
