### ISSUE TITLE
Closing main window now impossible.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#45]
makes it hard to quit the program!

``C:\users\sparks\projects\blackmirror\lib\platform.js:213 sending global {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: global, …} windowClose convopick: <<<
C:\users\sparks\projects\blackmirror\lib\platform.js:236 trapClose false true
C:\users\sparks\projects\blackmirror\lib\platform.js:196 got ipc: MessageEvent {isTrusted: true, data: {…}, origin: "file://", lastEventId: "", source: global, …}``

**Comment by SparksJ2** [comment]
Okay, sorry if I'm being vague but this is kind of messy...

Clicking directly on the journal name in the journal directory seems to often open the same convo twice, sometimes in separate windows, sometimes once in a separate window and once replacing the main window. I've not managed to capture console logs for these, partly due to the main window being overwritten (or closed maybe?), and partly due to the other problems below.

I've also had the 'It looks like this is your first time running BlackMirror.' popup several times now, not every run but maybe every 3rd or 4th run. I'm not sure where this info is stored, so I can't check on it. Might be being lost after the force-quits that I've had to use to close BM.

State of developer-mods is being lost between restarts as well, making getting console reports hard! I think maybe the hung processes are jamming the config file where data such as devmode status & conversation directory is being stored?

I also have many stray electron.exe processes left over in task manager and the command prompt where I'm running 'npm start from', sometimes I don't get my prompt back even after all the blackmirror windows are closed and have to Ctrl-C my way out there too.

Sorry for putting so much in one issue, but all this feels closely related.

Please see also https://github.com/sorentycho/blackmirror/issues/38 which may also be related and needs to be re-opened anyway.

**Comment by sorentycho** [comment]
It was all a part of the same mess around the Journal Manager's lifecycle. Fixed now, and I've added single-instance code which should cure the issues with global config getting reset (source of your occasionally having to reset dev mode) and straggling electron.exe's.

I altered the journal creation code to be stupider and thus hopefully avoid #38 from now on.
