### ISSUE TITLE
setting default voices in journal - menu display problem?

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#47]
steps:
create a new journal
open new journal
open journal menu and select default voices
close journal menu
re-open journal menu
voices selected do not show as selected

further:
close entire program
re-open program, then journal
check journal menu
voices selected DO show as selected

so it's saving which voices were selected (to _journal.yml), but not updating internally, it seems?

**Comment by sorentycho** [comment]
Closing because I removed this menu entirely as part of 7177d14bbbfc7d562fa05edcb76d6b91a5216203.
