### ISSUE TITLE
journal menu default voices have no effect?

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#48]
steps:
created new journal
set voices
(exited and reloaded program to avoid possible effects of previous issue #47)
re-opened journal
created new WIP entry
no voices in this new WIP seem to be set up?

file shows:
```---
voices:
  - __cycle
  - Me
name: 2019-06-02T13_07_29.05_+0100.wip.convo
lastSaver: '0.030144758490888712_1559477248952'
---
<p class="__cycle">test only!</p>
<p class="Me"><br></p>
```

and NOT the ones I selected in the journal viewer.

**Comment by sorentycho** [comment]
Seems fixed to me, so closing.
