### ISSUE TITLE
Width issue when window maximised.

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#9]
Div `<div class="ql-editor" data-gramm="false" contenteditable="true">` doesn't expand to the full width of the screen when the window is maximised. This leaves wide black borders on each side.

```
 #editor, .ql-editor {
        position: initial;
        height: auto;
        width: 100vw;
        overflow-y: visible;
      }
```
maybe set width: to 100%?

It'd be nice to have the full width of the screen available for editing even if I wouldn't normally do it.

**Comment by sorentycho** [comment]
Aww, my first WONTFIX on a public project! This is actually intentional because I like the text column not to get too wide.

However, it's easy to override in your custom styles: `html #editor { max-width: 100vw; }` (the `html` selector ensures that that rule will override the default stylesheet).
